### ISSUE TITLE
How to uninstall flashed IPC zip file?

### ISSUE THREAD

**Issue by cuongthm** [Magisk-Modules-Repo/ACSwitch#6]
Hello.

I have flashed IPC v3.0.1 zip file through recovery.
After reboot and running `ipc --info` command as root, it's stopped with output **Segmentation fault.**

Is there anyway to make it work?
If there isn't, how to uninstall it?

Please help, thanks.

**Comment by Jaymin-0-1910** [comment]
I guess you're rooted with Magisk already. Since currently I have no ways to help you debug due to resource unavailability to me, I'm gonna tell you how to uninstall it.
(I will soon perhaps ask you for debug logs as soon as I get back and setup my environment. (I have been detached from this world and all relevant for so long...).)
You simply need to remove `/data/adb/modules/IPControl` folder from recovery. Nothing more!

**Comment by Jaymin-0-1910** [comment]
I'm closing this issue, if your issue this persists, be free to reopen it:)
